SET DATABASE COLLATION "Latin1_General"
CREATE SCHEMA PUBLIC AUTHORIZATION DBA
CREATE CACHED TABLE "lnk_tbl"("lnk_id" NUMERIC(100) NOT NULL,"type_id" NUMERIC(100),"lnk_entry_id" NUMERIC(100),"lnk_meta_id" NUMERIC(100))
CREATE CACHED TABLE "toplevel_entries_tbl"("id" NUMERIC(100) NOT NULL PRIMARY KEY,"type_id" NUMERIC(100),"lnk_id" NUMERIC(100) NOT NULL,"lnk_type_id" NUMERIC(100))
CREATE CACHED TABLE "meta_tbl"("meta_id" NUMERIC(100) NOT NULL PRIMARY KEY,"status_id" NUMERIC(100),"author" VARCHAR(100),"date_of_entry" TIMESTAMP(0))
CREATE CACHED TABLE "types_tbl"("type_id" NUMERIC(100) NOT NULL PRIMARY KEY,"name" CHAR(2147483647))
CREATE USER SA PASSWORD ""
GRANT DBA TO SA
SET WRITE_DELAY 60
